version: '3'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "r00tClickBus0750**"
      MYSQL_DATABASE: "clickbus"
      MYSQL_USER: "clickbus"
      MYSQL_PASSWORD: "clickbus"
  php:
    build: "./docker/php" 
    volumes: 
      - .:/app
    links:
      - "mysql:basededatos"
  nginx:
    build: "./docker/nginx"
    ports: 
      - "8080:80"
    links:
      - "php:servidorphp"
    volumes:
      - .:/app